## Problem 1: Creating basic geometries (*5 points*)

In this problem you will create custom-made functions for creating geometries. We start with a very simple function, and proceed to creating functions that can handle invalid input values. 


1: Create a function called `create_point_geom()` that has two parameters (x_coord, y_coord). Function should create a shapely `Point` geometry object and return that. 
   

In [101]:
# REPLACE THE ERROR BELOW WITH YOUR OWN CODE

import shapely
from shapely.geometry import Point

def create_point_geom(x_coord,y_coord):
    """
    This function creates a shapely Point geometry object and returns it
    Parameter 1 - x_coord: Parameter for getting the x-coordinates
    Parameter 2 - x_coord: Parameter for getting the y-coordinates
    """
    point_geom = Point(x_coord, y_coord) #Creates Point Geometry
    
    return point_geom

Test your function by running these code cells:

In [102]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
# Demonstrate the usage of the function
point1 = create_point_geom(0.0, 1.1)

In [103]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(point1)

POINT (0 1.1)


In [104]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(point1.geom_type)

Point


2: Create a function called **`create_line_geom()`** that takes a list of Shapely Point objects as parameter called **`points`** and returns a LineString object of those input points. In addition, you should take care that the function is used as it should:

  - Inside the function, you should first check with `assert` -functionality that the input is a **list** (see [lesson 6 from the Geo-Python course](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints for this exercise](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a list!"`
  - You should also check with `assert` that the input list contains **at least** two values. If not, return an Error message: `"LineString object requires at least two Points!"`
  - Optional: Finally, you should check with `assert` that all values in the input list are truly Shapely Points. If not, return an Error message: `"All list values should be Shapely Point objects!"`
  

In [105]:
# REPLACE THE ERROR BELOW WITH YOUR OWN CODE

from shapely.geometry import LineString

#point2 = create_point_geom(45.2, 22.34)
#point3 = create_point_geom(100.22, -3.20)
#point4 = create_point_geom(70.0, 10.20)
#list_of_polypoints = [point2,point3,point4]

#print(point2)
#print(point3)
#print(point4)
#print(list_of_polypoints)

def create_line_geom(points):
    """
    This function accepts a list as a shapely point and
    returns it as a LineString object. 
    Parameter - points: List of Shapely Point Object/Shapely Point object.
    """
    assert type(points) == list, "Input should be a list!"  #Asserts whether the parameter is a list
    assert len(points) >= 2, "LineString object requires at least two Points!" #Asserts whether the list contains at least 2 shapely point objects
    
    #The two lines of code below asserts whether the values in the list are Shapely Point Obects
    
    #for element in points:
    #    assert type(element) == shapely.geometry.point.Point, "All list values should be Shapely Point objects!"
    
    line_geom = LineString(points)
    
    return line_geom 

Demonstrate the usage of your function; For example, create a line object with two points: `Point(45.2, 22.34)` & `Point(100.22, -3.20)` and store the result in a variable called `line1`:

In [106]:
list_of_points = [(45.2, 22.34), (100.22, -3.20)]
line1 = create_line_geom(list_of_points)

Run these code cells to check your solution:

In [107]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(line1)

LINESTRING (45.2 22.34, 100.22 -3.2)


In [108]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(line1.geom_type)

LineString


Check if your function checks the input correctly by running this code cell:

In [109]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a list
    create_line_geom("Give me a line!")
except AssertionError:
    print("Found an assertion error. List check works correctly.")
except Exception as e:
    raise e

Found an assertion error. List check works correctly.


3: Create a function called **`create_poly_geom()`** that has one parameter called **`coords`**. `coords` parameter should containt **a list of coordinate tuples**. The function should create and return a Polygon object based on these coordinates.  

  - Inside the function, you should first check with `assert` -functionality that the input is a **list** (see [lesson 6](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a list!"`
  - You should also check with `assert` that the input list contains **at least** three values. If not, return an Error message: `"Polygon object requires at least three Points!"`
  - Check the data type of the objects in the input list. All values in the input list should be tuples. If not, return an error message: "All list values should be coordinate tuples!" using assert.
  - **Optional:** Allow also an input containing a list of Shapely Point objects. If `coords` contains a list of Shapely Point objects, return a polygon based on these points. If the input is neither a list of tuples, nor a list of Points, return an appropriate error message using assert.
  

In [110]:
# REPLACE THE ERROR BELOW WITH YOUR OWN CODE

from shapely.geometry import Polygon

def create_poly_geom(coords):
    """
    This function takes in a list of coordinates tuples as input and returns
    a Shapely Polygon object.
    Parameter - coords: List of Coordinate tuples
    """
    assert type(coords) == list, "Input should be a list!" #Asserts whether the parameter is a list
    assert len(coords) >= 3, "Polygon object requires at least three Points!" #Asserts whether the list contains at least 3 shapely point objects
    #Asserts whether the data type of the objects in the input list are tuples or shapely point objects. 
    for element in coords:
        assert type(element) == tuple or type(element) == shapely.geometry.point.Point, "All list values should be coordinate tuples or Shapely Point Objects!"
    
    poly_geom = Polygon(coords)
    
    return poly_geom
        

Demonstrate the usage of the function. For example, create a Polygon with three points: `(45.2, 22.34)`, `(100.22, -3.20)` & `(70.0, 10.20)`.

In [111]:
list_of_poly = [(45.2, 22.34), (100.22, -3.20), (70.0, 10.20)] #Values in the list are tuples

poly1 = create_poly_geom(list_of_poly)
#The line of code below confirms that Shapely Point Objects are also accepted in the list of the input parameter of function "create_poly_geom"
#poly2 = create_poly_geom(list_of_polypoints) 

In [112]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(poly1)

POLYGON ((45.2 22.34, 100.22 -3.2, 70 10.2, 45.2 22.34))


In [113]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(poly1.geom_type)

Polygon


Check if your function checks the length of the input correctly by running this code cell:

In [114]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a list
    create_poly_geom("Give me a polygon")
except AssertionError:
    print("List check works")
except Exception as e:
    raise e

List check works


Remember to commit your code using git after each major code change (for example, after solving each problem). Remember also to upload (push) your files to your **own** personal GitHub repository for Exercise-1.

## Done!

That's it. Now you are ready to continue with Problem 2. 

## Problem 2: Attributes of geometries (*5 points*)

1: Create a function called `get_centroid()` that has one parameter called `geom`. The function should take any kind of Shapely's geometric -object as an input, and return a centroid of that geometry. In addition, you should take care that the function is used as it should:

  - Inside the function, you should first check with `assert` -functionality that the input is a Shapely Point, LineString or Polygon geometry (see [lesson 6](https://autogis-site.readthedocs.io/en/latest/lessons/L1/exercise-1.html#hints) from the Geo-Python couurse and [hints](https://autogis-site.readthedocs.io/en/latest/lessons/L1/exercise-1.html#hints) for help). If something else than a list is passed for the function, you should return an Error message: `"Input should be a Shapely geometry!"`


In [115]:
# REPLACE THE ERROR BELOW WITH YOUR OWN CODE

def get_centroid(geom):
    """
    This function takes in any kind of Shapely's geometry object and returns the centroid of that geometry.
    Parameter - geom: Shapely's Geometry Object
    """
    #The code below asserts whether the input parameter is a Shapely Geometry Object.
    assert type(geom) in [shapely.geometry.point.Point, shapely.geometry.linestring.LineString, shapely.geometry.polygon.Polygon], "Input should be a Shapely geometry!"
    
    gt_centroid = geom.centroid
    
    return gt_centroid

Test and demonstrate the usage of the function. You can, for example, create shapely objects using the functions you created in problem 1 and print out information about their centroids:


In [116]:
line1_centroid = get_centroid(line1)
print(line1_centroid)

POINT (72.71000000000001 9.57)


In [117]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
centroid = get_centroid(poly1)
print(centroid)

POINT (71.80666666666667 9.780000000000001)


Check that the assertion error works correctly:

In [118]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a Shapely geometry
    get_centroid("Give me a centroid!")
except AssertionError:
    print("Found and assertion error. Geometry -check works correctly.")
except Exception as e:
    raise e

Found and assertion error. Geometry -check works correctly.


2: Create a function called `get_area()` with one parameter called `polygon`. Function should take a Shapely's Polygon -object as input and returns the area of that geometry. 
   
   - Inside the function, you should first check with `assert` -functionality that the input is a Shapely Polygon geometry (see [lesson 6](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a Shapely Polygon -object!"`

In [119]:
# REPLACE THE ERROR BELOW WITH YOUR OWN CODE

def get_area(polygon):
    """
    This function takes in a Shapely Polygon Object and returns the area of that geometry.
    Parameter - polygon: Shapely Polygon Object
    """
    assert type(polygon) == shapely.geometry.polygon.Polygon, "Input should be a Shapely Polygon -object!" #Asserts whether the input parameter is a Shapely Polygon Object
    
    gt_area = polygon.area
    
    return gt_area
    

Test and demonstrate the usage of the function:

In [120]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
area = get_area(poly1)
print(round(area, 2))

17.28


Check that the assertion works:

In [121]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a Shapely geometry
    get_area("Give me an area!")
except AssertionError:
    print("Geometry -check works")
except Exception as e:
    raise e

Geometry -check works


3: Create a function called `get_length()` with parameter called `geom`. The function should accept either a Shapely LineString or Polygon -object as input. Function should check the type of the input and returns the length of 
the line if input is LineString and length of the exterior ring if input is Polygon. If something else is passed to the function, you should return an `Error` `"'geom' should be either LineString or Polygon!"`. (Use assert functionality). 


In [122]:
# REPLACE THE ERROR BELOW WITH YOUR OWN CODE

def get_length(geom):
    """
    This function takes in either a Shapely LineString or Polygon Object
    and returns the length of the ine if it's a LineString and length of the
    exterior ring if it's a Polygon.
    Parameter - geom: Shapely LineString or Polygon Object.
    """
    #The code below asserts whether the input paraneter is a Shapely LineString or Polygon Obect.
    assert type(geom) in [shapely.geometry.linestring.LineString, shapely.geometry.polygon.Polygon], "'geom' should be either LineString or Polygon!"
    
    if type(geom) == shapely.geometry.linestring.LineString:
        return geom.length
    else:
        return geom.exterior.length
    

Test and demonstrate the usage of the function:

In [123]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
line_length = get_length(line1)
print("Line length:", round(line_length,2))

Line length: 60.66


In [124]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
poly_exterior_length = get_length(poly1)
print("Polygon exterior length:", round(poly_exterior_length,2))

Polygon exterior length: 121.33


In [125]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a Shapely LineString or Polygon
    get_length(Point(1,2))
except AssertionError:
    print("Geometry -check works")
except Exception as e:
    raise e

Geometry -check works


## Docstrings

Did you add a docstring to all the functions you defined? If not, add them now :) A short one-line docstring is enough in this exercise.

YOUR ANSWER HERE

In addition, you can run the code cell below to check all the docstrings!

In [126]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION

# List all functions we created
functions = [create_point_geom, create_line_geom, create_poly_geom, 
             get_centroid, get_area, get_length]

print("My funcitions:\n")

for function in functions:
    #Print function name and docstring:
    print("-", function.__name__ +":", function.__doc__)

My funcitions:

- create_point_geom: 
    This function creates a shapely Point geometry object and returns it
    Parameter 1 - x_coord: Parameter for getting the x-coordinates
    Parameter 2 - x_coord: Parameter for getting the y-coordinates
    
- create_line_geom: 
    This function accepts a list as a shapely point and
    returns it as a LineString object. 
    Parameter - points: List of Shapely Point Object/Shapely Point object.
    
- create_poly_geom: 
    This function takes in a list of coordinates tuples as input and returns
    a Shapely Polygon object.
    Parameter - coords: List of Coordinate tuples
    
- get_centroid: 
    This function takes in any kind of Shapely's geometry object and returns the centroid of that geometry.
    Parameter - geom: Shapely's Geometry Object
    
- get_area: 
    This function takes in a Shapely Polygon Object and returns the area of that geometry.
    Parameter - polygon: Shapely Polygon Object
    
- get_length: 
    This function ta

- Upload the codes and edits to your **own** personal GitHub repository for Exercise-1.

## Done!

That's it. Now you are ready to continue with Problem 3. 